version: '3.9'

services:
  NodeInterestelar:
    container_name: interestelarapp
    restart: always
    image: node
    build: .
    ports:
      - 5161:3000
    volumes:
      - .:/usr/src/app
    links:
     - mongo
     
  mongo:
    container_name: mongodb
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root  
      - MONGO_INITDB_ROOT_PASSWORD=root  
    command: 
      mongod --quiet --logpath /dev/null 
    ports:
      - 5162:27017
    volumes:
      - ./mongo_data:/data/db